// SPDX-FileCopyrightText: Steven Ward
// SPDX-License-Identifier: MPL-2.0

/// AES-CTR-128 PRNG
/**
* \file
* \author Steven Ward
*/

#pragma once

#include "aes128-utils.h"
#include "aes_ctr_128_prng-defaults.h"

#include <err.h>
#include <immintrin.h>
#include <stdlib.h>
#include <unistd.h>

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(AESCTR128_PRNG_NUM_KEYS)
#define AESCTR128_PRNG_NUM_KEYS DEFAULT_AESCTR128_PRNG_NUM_KEYS
#endif

#if !defined(AESCTR128_PRNG_NUM_ROUNDS_PER_KEY)
#define AESCTR128_PRNG_NUM_ROUNDS_PER_KEY DEFAULT_AESCTR128_PRNG_NUM_ROUNDS_PER_KEY
#endif

/// A PRNG that uses AES instructions
struct aes_ctr_128_prng
{
    static_assert(AESCTR128_PRNG_NUM_KEYS >= 1);
    static_assert(AESCTR128_PRNG_NUM_ROUNDS_PER_KEY >= 1);
    static_assert(AESCTR128_PRNG_NUM_KEYS * AESCTR128_PRNG_NUM_ROUNDS_PER_KEY >= 3,
                  "must do at least 3 rounds of AES enc/dec");

    __m128i keys[AESCTR128_PRNG_NUM_KEYS];
    __m128i ctr; ///< The state/counter
};

typedef struct aes_ctr_128_prng aes_ctr_128_prng;

static_assert(sizeof(aes_ctr_128_prng) <= 256,
              "getentropy will fail if more than 256 bytes are requested");

/// Assign random bytes to the data members via \c getentropy.
/**
* \note This function terminates the calling process upon catastrophic error.
*/
static void
aes_ctr_128_prng_reseed(aes_ctr_128_prng* this_)
{
    if (getentropy(this_, sizeof(*this_)) < 0)
        err(EXIT_FAILURE, "getentropy");
}

/// Get the next PRNG output via AES encryption.
static inline __m128i
aes_ctr_128_prng_enc_next(aes_ctr_128_prng* this_)
{
    /*
    * Criteria for integers of \c inc:
    *   1) Must be odd
    *   2) Must be unique
    *   3) Should have half the bits set
    *
    * Integers of \c inc were generated by the script `patterned_primes.py`.
    *
    * \sa https://en.wikipedia.org/wiki/Weyl_sequence#In_computing
    */

    // most significant elem first
    const __m128i inc = _mm_set_epi32(0x4a535aab, 0x55952d55, 0x6accb295, 0xad659529);

    const __m128i dst = aes128_enc(this_->ctr, this_->keys, AESCTR128_PRNG_NUM_KEYS,
                                   AESCTR128_PRNG_NUM_ROUNDS_PER_KEY);

    this_->ctr = _mm_add_epi32(this_->ctr, inc);

    return dst;
}

/// Get the next PRNG output via AES decryption.
static inline __m128i
aes_ctr_128_prng_dec_next(aes_ctr_128_prng* this_)
{
    // most significant elem first
    const __m128i inc = _mm_set_epi32(0x4a535aab, 0x55952d55, 0x6accb295, 0xad659529);

    const __m128i dst = aes128_dec(this_->ctr, this_->keys, AESCTR128_PRNG_NUM_KEYS,
                                   AESCTR128_PRNG_NUM_ROUNDS_PER_KEY);

    this_->ctr = _mm_add_epi32(this_->ctr, inc);

    return dst;
}

/// Get the next PRNG output via AES encryption and Davies-Meyer single-block-length compression function.
static inline __m128i
aes_ctr_128_prng_enc_davies_meyer_next(aes_ctr_128_prng* this_)
{
    // most significant elem first
    const __m128i inc = _mm_set_epi32(0x4a535aab, 0x55952d55, 0x6accb295, 0xad659529);

    const __m128i dst = aes128_enc_davies_meyer(
        this_->ctr, this_->keys, AESCTR128_PRNG_NUM_KEYS, AESCTR128_PRNG_NUM_ROUNDS_PER_KEY);

    this_->ctr = _mm_add_epi32(this_->ctr, inc);

    return dst;
}

/// Get the next PRNG output via AES decryption and Davies-Meyer single-block-length compression function.
static inline __m128i
aes_ctr_128_prng_dec_davies_meyer_next(aes_ctr_128_prng* this_)
{
    // most significant elem first
    const __m128i inc = _mm_set_epi32(0x4a535aab, 0x55952d55, 0x6accb295, 0xad659529);

    const __m128i dst = aes128_dec_davies_meyer(
        this_->ctr, this_->keys, AESCTR128_PRNG_NUM_KEYS, AESCTR128_PRNG_NUM_ROUNDS_PER_KEY);

    this_->ctr = _mm_add_epi32(this_->ctr, inc);

    return dst;
}

#ifdef __cplusplus
}
#endif
